create extension if not exists pgcrypto;
create table if not exists users (id uuid primary key default gen_random_uuid(), email text not null unique, password_hash text not null, full_name text not null, role text not null default 'student' check (role in ('student','admin','ambassador')), phone text, university text, department text, referral_code text unique, created_at timestamptz not null default now());
create table if not exists project_topics (id uuid primary key default gen_random_uuid(), title text not null, department text not null, level text not null default 'Intermediate', price numeric(12,2) not null default 0, short_description text not null default '', introduction text, aim_objectives text, scope_limitations text, methodology text, icon text not null default 'auto_stories', accent text not null default 'coral', featured boolean not null default false, is_published boolean not null default true, created_at timestamptz not null default now());
create table if not exists orders (id uuid primary key default gen_random_uuid(), user_id uuid not null references users(id) on delete cascade, topic_id uuid references project_topics(id) on delete set null, status text not null default 'pending' check(status in ('pending','in_review','awaiting_brief','paid','completed','cancelled')), amount numeric(12,2) not null default 0, due_date date, payment_reference text, invoice_url text, created_at timestamptz not null default now());
create table if not exists project_files (id uuid primary key default gen_random_uuid(), topic_id uuid references project_topics(id) on delete cascade, order_id uuid references orders(id) on delete cascade, file_name text not null, file_type text not null default 'document', file_url text not null, created_at timestamptz not null default now());
create table if not exists faqs (id uuid primary key default gen_random_uuid(), question text not null, answer text not null, category text not null default 'General', sort_order integer not null default 0, is_published boolean not null default true);
create table if not exists referrals (id uuid primary key default gen_random_uuid(), referrer_id uuid not null references users(id) on delete cascade, referred_email text not null, status text not null default 'invited', commission numeric(12,2) not null default 0, created_at timestamptz not null default now());
create table if not exists ambassador_applications (id uuid primary key default gen_random_uuid(), user_id uuid references users(id) on delete set null, full_name text not null, email text not null, school text not null, course text not null, level text not null, status text not null default 'pending', created_at timestamptz not null default now());
create table if not exists notifications (id uuid primary key default gen_random_uuid(), user_id uuid references users(id) on delete cascade, title text not null, body text not null, read_at timestamptz, created_at timestamptz not null default now());
insert into project_topics(title,department,level,price,short_description,icon,accent,featured) values
('Smart Campus Attendance System','Computer Science','Intermediate',28000,'A practical system for secure attendance capture, reporting, and student analytics.','qr_code_scanner','coral',true),
('AI-Based Timetable Scheduling','Artificial Intelligence','Advanced',32000,'Generate optimized academic timetables using genetic algorithms and constraints.','calendar_month','blue',true),
('E-commerce Inventory Platform','Software Engineering','Intermediate',26500,'Build a resilient inventory and order management workflow for growing sellers.','inventory_2','mint',true),
('Hospital Appointment Portal','Health Informatics','Intermediate',24000,'Design an accessible portal that connects patients, doctors, and records.','local_hospital','sand',false),
('Microfinance Credit Scoring Model','Data Science','Advanced',35000,'Explore interpretable scoring models for responsible lending decisions.','query_stats','violet',false),
('Smart Irrigation Monitor','Electrical Engineering','Advanced',31000,'A sensor-led IoT project for measuring and responding to soil conditions.','water_drop','teal',false)
on conflict do nothing;
insert into faqs(question,answer,category,sort_order) values
('How do I choose a project topic?','Start with a department filter, read the brief, and compare the scope with your skills, timeline, and supervisor expectations.','Getting started',1),
('What happens after I place an order?','A project guide reviews your brief, confirms the delivery plan, and keeps milestones visible from your dashboard.','Orders',2),
('Can I request a custom service?','Yes. Use the Services page to request proposal drafting, documentation, source code, or a custom build.','Services',3),
('How do payments work?','Payments are processed server-side through your configured payment provider. Your invoice and payment state remain attached to the order.','Payments',4)
on conflict do nothing;
