import { Body, ConflictException, Controller, ForbiddenException, Get, Inject, Module, NotFoundException, Param, Patch, Post, Put, Req, UseGuards } from '@nestjs/common';
import { IsEmail, IsIn, IsInt, IsNumber, IsOptional, IsString, IsUUID, Max, Min, MinLength } from 'class-validator';
import { Pool } from 'pg';
import { AuthModule } from '../auth/auth.module';
import { AuthenticatedRequest, JwtAuthGuard } from '../auth/jwt-auth.guard';

export class CreateOrderDto { @IsUUID() topic_id!:string; @IsOptional() @IsString() @MinLength(10) brief?:string; }
export class UpdateBriefDto { @IsString() @MinLength(2) title!:string; @IsString() objectives!:string; @IsString() scope!:string; @IsString() methodology!:string; @IsOptional() @IsString() supervisor_notes?:string; }
export class ServiceRequestDto { @IsString() service_type!:string; @IsString() @MinLength(3) title!:string; @IsString() @MinLength(10) description!:string; @IsOptional() @IsNumber() budget?:number; }
export class ProfileUpdateDto { @IsOptional() @IsString() @MinLength(2) full_name?:string; @IsOptional() @IsString() phone?:string; @IsOptional() @IsString() university?:string; @IsOptional() @IsString() department?:string; }
export class FileDto { @IsUUID() order_id!:string; @IsString() file_name!:string; @IsString() file_type!:string; @IsString() file_url!:string; }
export class ReviewDto { @IsInt() @Min(1) @Max(5) rating!:number; @IsOptional() @IsString() comment?:string; }
export class ReferralDto { @IsEmail() referred_email!:string; }
export class AmbassadorDto { @IsString() full_name!:string; @IsEmail() email!:string; @IsString() school!:string; @IsString() course!:string; @IsString() level!:string; }

function adminOnly(req:AuthenticatedRequest){ if(req.user.role!=='admin') throw new ForbiddenException('Admin access required'); }

@Controller('orders')
@UseGuards(JwtAuthGuard)
export class WorkflowOrdersController {
  constructor(@Inject('PG_POOL') private readonly pool:Pool) {}
  @Get('summary') async summary(@Req() req:AuthenticatedRequest){ const {rows}=await this.pool.query(`select o.id,o.status,o.amount,o.payment_status,o.service_type,o.brief,o.created_at,o.updated_at,o.due_date,p.title as project_title,p.department from orders o left join project_topics p on p.id=o.topic_id where o.user_id=$1 order by o.created_at desc limit 30`,[req.user.sub]); return rows; }
  @Post() async create(@Req() req:AuthenticatedRequest,@Body() dto:CreateOrderDto){ const topic=await this.pool.query('select id,title,price from project_topics where id=$1 and is_published=true limit 1',[dto.topic_id]); if(!topic.rows[0]) throw new NotFoundException('Project topic not found'); const client=await this.pool.connect(); try { await client.query('begin'); const order=await client.query(`insert into orders(user_id,topic_id,status,amount,brief) values($1,$2,'awaiting_brief',$3,$4) returning id,user_id,topic_id,status,amount,payment_status,brief,created_at`,[req.user.sub,dto.topic_id,topic.rows[0].price,dto.brief||'']); await client.query(`insert into order_events(order_id,actor_id,event_type,note) values($1,$2,'order_created',$3)`,[order.rows[0].id,req.user.sub,'Order created from project topic']); await client.query(`insert into notifications(user_id,title,body) values($1,'Order received','Your project request is now in the workspace.')`,[req.user.sub]); await client.query('commit'); return {...order.rows[0],project_title:topic.rows[0].title}; } catch(e){ await client.query('rollback'); throw e; } finally { client.release(); } }
  @Get(':id') async detail(@Req() req:AuthenticatedRequest,@Param('id') id:string){ const {rows}=await this.pool.query(`select o.*,p.title as project_title,p.department from orders o left join project_topics p on p.id=o.topic_id where o.id=$1 and o.user_id=$2 limit 1`,[id,req.user.sub]); if(!rows[0]) throw new NotFoundException('Order not found'); const [brief,events,files,review]=await Promise.all([this.pool.query('select * from project_briefs where order_id=$1',[id]),this.pool.query('select event_type,note,created_at from order_events where order_id=$1 order by created_at asc',[id]),this.pool.query('select id,file_name,file_type,file_url,created_at from project_files where order_id=$1 order by created_at desc',[id]),this.pool.query('select rating,comment,created_at from reviews where order_id=$1',[id])]); return {...rows[0],brief:brief.rows[0]||null,events:events.rows,files:files.rows,review:review.rows[0]||null}; }
  @Put(':id/brief') async brief(@Req() req:AuthenticatedRequest,@Param('id') id:string,@Body() dto:UpdateBriefDto){ await this.assertOwned(id,req.user.sub); const {rows}=await this.pool.query(`insert into project_briefs(order_id,title,objectives,scope,methodology,supervisor_notes,status) values($1,$2,$3,$4,$5,$6,'submitted') on conflict(order_id) do update set title=excluded.title,objectives=excluded.objectives,scope=excluded.scope,methodology=excluded.methodology,supervisor_notes=excluded.supervisor_notes,status='submitted',updated_at=now() returning *`,[id,dto.title,dto.objectives,dto.scope,dto.methodology,dto.supervisor_notes||'']); await this.pool.query(`update orders set status='in_review',updated_at=now() where id=$1`,[id]); return rows[0]; }
  @Post(':id/pay') async pay(@Req() req:AuthenticatedRequest,@Param('id') id:string){ await this.assertOwned(id,req.user.sub); const reference=`demo_${Date.now()}`; const {rows}=await this.pool.query(`update orders set status='paid',payment_status='paid',payment_reference=$2,updated_at=now() where id=$1 returning id,status,payment_status,payment_reference,amount`,[id,reference]); if(!rows[0]) throw new NotFoundException('Order not found'); await this.pool.query(`insert into order_events(order_id,actor_id,event_type,note) values($1,$2,'payment_confirmed','Payment confirmed by configured payment adapter')`,[id,req.user.sub]); return rows[0]; }
  @Post(':id/cancel') async cancel(@Req() req:AuthenticatedRequest,@Param('id') id:string){ await this.assertOwned(id,req.user.sub); const {rows}=await this.pool.query(`update orders set status='cancelled',cancelled_at=now(),updated_at=now() where id=$1 and status not in ('completed','cancelled') returning id,status,cancelled_at`,[id]); if(!rows[0]) throw new ConflictException('Order cannot be cancelled at its current status'); await this.pool.query(`insert into order_events(order_id,actor_id,event_type,note) values($1,$2,'order_cancelled','Order cancelled by customer')`,[id,req.user.sub]); return rows[0]; }
  @Post(':id/review') async review(@Req() req:AuthenticatedRequest,@Param('id') id:string,@Body() dto:ReviewDto){ await this.assertOwned(id,req.user.sub); const {rows}=await this.pool.query(`insert into reviews(order_id,user_id,rating,comment) values($1,$2,$3,$4) on conflict(order_id) do update set rating=excluded.rating,comment=excluded.comment returning *`,[id,req.user.sub,dto.rating,dto.comment||'']); return rows[0]; }
  private async assertOwned(id:string,userId:string){ const result=await this.pool.query('select id from orders where id=$1 and user_id=$2 limit 1',[id,userId]); if(!result.rows[0]) throw new NotFoundException('Order not found'); }
}

@Controller('profile')
@UseGuards(JwtAuthGuard)
export class ProfileController { constructor(@Inject('PG_POOL') private readonly pool:Pool) {} @Get() async get(@Req() req:AuthenticatedRequest){ const {rows}=await this.pool.query('select id,email,full_name,role,phone,university,department,referral_code,created_at from users where id=$1',[req.user.sub]); return rows[0]; } @Patch() async update(@Req() req:AuthenticatedRequest,@Body() dto:ProfileUpdateDto){ const {rows}=await this.pool.query(`update users set full_name=coalesce($2,full_name),phone=coalesce($3,phone),university=coalesce($4,university),department=coalesce($5,department) where id=$1 returning id,email,full_name,role,phone,university,department,referral_code`,[req.user.sub,dto.full_name,dto.phone,dto.university,dto.department]); return rows[0]; } }

@Controller('services')
@UseGuards(JwtAuthGuard)
export class ServicesController { constructor(@Inject('PG_POOL') private readonly pool:Pool) {} @Get() async list(@Req() req:AuthenticatedRequest){ const {rows}=await this.pool.query('select * from service_requests where user_id=$1 order by created_at desc',[req.user.sub]); return rows; } @Post() async create(@Req() req:AuthenticatedRequest,@Body() dto:ServiceRequestDto){ const {rows}=await this.pool.query('insert into service_requests(user_id,service_type,title,description,budget) values($1,$2,$3,$4,$5) returning *',[req.user.sub,dto.service_type,dto.title,dto.description,dto.budget||null]); return rows[0]; } }

@Controller('files')
@UseGuards(JwtAuthGuard)
export class FilesController { constructor(@Inject('PG_POOL') private readonly pool:Pool) {} @Get('order/:orderId') async list(@Req() req:AuthenticatedRequest,@Param('orderId') orderId:string){ await this.owned(orderId,req.user.sub); const {rows}=await this.pool.query('select id,file_name,file_type,file_url,created_at from project_files where order_id=$1 order by created_at desc',[orderId]); return rows; } @Post() async add(@Req() req:AuthenticatedRequest,@Body() dto:FileDto){ await this.owned(dto.order_id,req.user.sub); const {rows}=await this.pool.query('insert into project_files(order_id,file_name,file_type,file_url) values($1,$2,$3,$4) returning *',[dto.order_id,dto.file_name,dto.file_type,dto.file_url]); return rows[0]; } private async owned(id:string,userId:string){ const result=await this.pool.query('select id from orders where id=$1 and user_id=$2',[id,userId]); if(!result.rows[0]) throw new NotFoundException('Order not found'); } }

@Controller('referrals')
@UseGuards(JwtAuthGuard)
export class ReferralsController { constructor(@Inject('PG_POOL') private readonly pool:Pool) {} @Get() async list(@Req() req:AuthenticatedRequest){ const {rows}=await this.pool.query('select * from referrals where referrer_id=$1 order by created_at desc',[req.user.sub]); return rows; } @Post() async create(@Req() req:AuthenticatedRequest,@Body() dto:ReferralDto){ const {rows}=await this.pool.query('insert into referrals(referrer_id,referred_email) values($1,lower($2)) returning *',[req.user.sub,dto.referred_email]); return rows[0]; } }

@Controller('ambassador')
export class AmbassadorController { constructor(@Inject('PG_POOL') private readonly pool:Pool) {} @Post('apply') async apply(@Req() req:AuthenticatedRequest,@Body() dto:AmbassadorDto){ const userId=req.user?.sub||null; const {rows}=await this.pool.query('insert into ambassador_applications(user_id,full_name,email,school,course,level) values($1,$2,$3,$4,$5,$6) returning *',[userId,dto.full_name,dto.email,dto.school,dto.course,dto.level]); return rows[0]; } @Get('mine') @UseGuards(JwtAuthGuard) async mine(@Req() req:AuthenticatedRequest){ const {rows}=await this.pool.query('select * from ambassador_applications where user_id=$1 order by created_at desc',[req.user.sub]); return rows; } }

@Controller('notifications')
@UseGuards(JwtAuthGuard)
export class NotificationsController { constructor(@Inject('PG_POOL') private readonly pool:Pool) {} @Get() async list(@Req() req:AuthenticatedRequest){ const {rows}=await this.pool.query('select * from notifications where user_id=$1 order by created_at desc limit 50',[req.user.sub]); return rows; } @Post(':id/read') async markRead(@Req() req:AuthenticatedRequest,@Param('id') id:string){ const {rows}=await this.pool.query('update notifications set read_at=now() where id=$1 and user_id=$2 returning *',[id,req.user.sub]); if(!rows[0]) throw new NotFoundException('Notification not found'); return rows[0]; } }

@Controller('admin')
@UseGuards(JwtAuthGuard)
export class AdminController { constructor(@Inject('PG_POOL') private readonly pool:Pool) {} @Get('orders') async orders(@Req() req:AuthenticatedRequest){ adminOnly(req); const {rows}=await this.pool.query(`select o.id,o.status,o.amount,o.payment_status,o.created_at,u.email,u.full_name,p.title as project_title from orders o join users u on u.id=o.user_id left join project_topics p on p.id=o.topic_id order by o.created_at desc limit 100`); return rows; } @Patch('orders/:id/status') async updateOrder(@Req() req:AuthenticatedRequest,@Param('id') id:string,@Body('status') status:string){ adminOnly(req); const allowed=['pending','in_review','awaiting_brief','paid','completed','cancelled']; if(!allowed.includes(status)) throw new ConflictException('Unsupported order status'); const {rows}=await this.pool.query('update orders set status=$2,updated_at=now() where id=$1 returning *',[id,status]); if(!rows[0]) throw new NotFoundException('Order not found'); return rows[0]; } @Get('users') async users(@Req() req:AuthenticatedRequest){ adminOnly(req); const {rows}=await this.pool.query('select id,email,full_name,role,university,department,created_at from users order by created_at desc limit 100'); return rows; } }

@Module({imports:[AuthModule],controllers:[WorkflowOrdersController,ProfileController,ServicesController,FilesController,ReferralsController,AmbassadorController,NotificationsController,AdminController]})
export class WorkflowsModule {}
